// AUTO-GENERATED by ml/train_tinyml_model.py -- do not hand-edit.
// Re-run that script (see its module docstring) to regenerate this
// file from a new dataset instead of editing the numbers below.
#pragma once

#define TINYML_N_FEATURES 8
#define TINYML_HIDDEN_SIZE 6

// Feature order used everywhere below and in worker_n.ino's
// buildFeatureVector(): temperatureC, humidityPct, airQualityRaw, combustibleGasRaw, heartRateBpm, spo2Pct, soilMoisturePct, motionEnergy.

const float TINYML_FEATURE_MIN[8] = { 18.00000000f, 25.00000000f, 150.00000000f, 100.00000000f, 52.00000000f, 92.00000000f, 3.00000000f, 0.00000000f };
const float TINYML_FEATURE_MAX[8] = { 34.00000000f, 85.00000000f, 1600.00000000f, 3400.00000000f, 128.00000000f, 100.00000000f, 72.00000000f, 5.00000000f };

const float TINYML_W1[8][6] = { -0.29704015f, -0.10315762f, -1.21033600f, 0.33028856f, -0.28719868f, 0.83838707f, 0.97627420f, -1.25118322f, 0.03991766f, 0.09409559f, 0.21692801f, 0.58205165f, -0.00601361f, 0.45242435f, 1.27995392f, 0.09057824f, -0.70694757f, 0.80007826f, 1.13788302f, 0.16365805f, 0.13179558f, 0.12700290f, -0.01423840f, -1.05851549f, -0.96227148f, -0.95774963f, 0.60343541f, 0.35421188f, -0.65770621f, -0.38907021f, 0.09307175f, -0.46696737f, -0.59220426f, -1.22295524f, 0.03409146f, -0.02498823f, 0.07268537f, 0.21868304f, -0.38145384f, 1.15868001f, -0.81411625f, -0.69608477f, -0.93804616f, -0.55305425f, -0.02391572f, -0.98904445f, -0.51641215f, -0.86296450f };
const float TINYML_B1[6] = { -0.17550085f, 1.00912065f, 0.03254776f, -0.20383704f, -0.34010151f, 0.19676597f };
const float TINYML_W2[6][8] = { -0.44292800f, 1.11114707f, -0.05374676f, 1.26914476f, -1.06211631f, 0.42854388f, -0.10331515f, -1.03258069f, -0.26151512f, -1.80230362f, 0.37045787f, 0.04566687f, -1.36460808f, -0.28167127f, -0.02073928f, -0.40288219f, -1.30054593f, 0.19287892f, 1.40590270f, 0.13910742f, 0.67372907f, -0.53089452f, -0.52106222f, 0.14980230f, 0.57904247f, 0.24503505f, -0.03157285f, -0.04366300f, 0.76357119f, -1.26541390f, 1.42072220f, -1.02199678f, -0.37907403f, 0.15862352f, -0.15513077f, -0.17257728f, 0.13428010f, 0.15426455f, -0.27923117f, 0.32831403f, 0.84972589f, 0.59223849f, 0.84760081f, -1.22026835f, -0.39202471f, 0.03802910f, -0.79759768f, -1.12711645f };
const float TINYML_B2[8] = { -0.36646316f, -0.13385036f, -0.10635735f, -0.19837073f, 0.16732589f, 0.01839265f, -0.37854082f, -0.81501525f };

const float TINYML_ANOMALY_THRESHOLD = 0.03549841f;

// Per-sensor threshold band derived from the training data's own
// mean +/- 3 standard deviations, clamped so it can never claim a
// value is 'safe' beyond the hard physical safety ceiling for that
// sensor (see HARD_SAFETY_BOUND in the training script). Reported
// to the dashboard as each sensor's live ML-derived threshold.
const float TINYML_FEATURE_LOW_THRESHOLD[8] = { 17.92533732f, 25.23278184f, 161.99353114f, 87.51421234f, 55.68795872f, 91.50209969f, 3.39778388f, -1.44705699f };
const float TINYML_FEATURE_HIGH_THRESHOLD[8] = { 33.99278881f, 85.14429838f, 1604.08963114f, 3426.25566085f, 130.00000000f, 99.68713546f, 71.34016919f, 3.94928716f };

